/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ITaxpayerModel;
import Model.TaxPayer;
import Presenter.TaxPayerPresenter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilove
 */
public class TaxPayerView extends javax.swing.JFrame implements ITaxPayerView {

    private TaxPayerPresenter presenter;
    List<TaxPayer> taxPayer;

    public TaxPayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JToggleButton();
        browseBtn = new javax.swing.JToggleButton();
        nextBtn = new javax.swing.JToggleButton();
        updteBtn = new javax.swing.JToggleButton();
        preBtn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pageNumText = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        sumPageNumText = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfnText = new javax.swing.JTextField();
        frstName = new javax.swing.JTextField();
        lstNameText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addrssText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        incmeTxt = new javax.swing.JTextField();
        deductbleTxt = new javax.swing.JTextField();
        txReturnedTxt = new javax.swing.JTextField();
        txHeldTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfnSearch = new javax.swing.JTextField();
        tfnSearchBtn = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lastNameSearch = new javax.swing.JTextField();
        lstNameSearchBtn = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        browseBtn.setText("Browse All");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        nextBtn.setText(">>Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        updteBtn.setText("Update");
        updteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updteBtnActionPerformed(evt);
            }
        });

        preBtn.setText("Previous<<");
        preBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(pageNumText);

        jScrollPane3.setViewportView(sumPageNumText);

        jLabel1.setText("Of");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Tax Record System");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data Enry, Browse and Query   ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Personal Data ");

        jLabel5.setText("TFN");

        jLabel6.setText("First name");

        jLabel7.setText("Last name");

        jLabel8.setText("Address");

        addrssText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrssTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Phone");

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Income");

        jLabel11.setText("Deductible ");

        jLabel12.setText("Tax held");

        jLabel13.setText("Tax to be returned");

        txReturnedTxt.setEditable(false);

        txHeldTxt.setEditable(false);
        txHeldTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHeldTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addrssText))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfnText)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(frstName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txHeldTxt))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(incmeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lstNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(phoneText, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(deductbleTxt)
                            .addComponent(txReturnedTxt)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tfnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addrssText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(incmeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductbleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txReturnedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txHeldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Find entry by TFN");

        tfnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnSearchActionPerformed(evt);
            }
        });

        tfnSearchBtn.setText("Search");
        tfnSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(tfnSearchBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnSearchBtn))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Find entry by Last Name");

        lastNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameSearchActionPerformed(evt);
            }
        });

        lstNameSearchBtn.setText("Search");
        lstNameSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstNameSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lastNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(lstNameSearchBtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstNameSearchBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jToggleButton3.setText("Exit");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton3)
                                .addGap(29, 29, 29)))
                        .addGap(305, 305, 305))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(browseBtn)
                                .addGap(18, 18, 18)
                                .addComponent(preBtn)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(updteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 93, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(browseBtn)
                        .addComponent(preBtn)
                        .addComponent(updteBtn)
                        .addComponent(nextBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jToggleButton3)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (tfnText.getText().trim().isEmpty()) {//text field excepton handling 
            showMessageDialog("TFN must be entered", "Error");
            showMessageDialog("Tax Payer not added", "Error");
            return;
        }
        if (frstName.getText().trim().isEmpty()) {
            showMessageDialog("First Name must be entered", "Error");
            showMessageDialog("Tax Payer not added", "Error");
            return;
        }
        if (lstNameText.getText().trim().isEmpty()) {
            showMessageDialog("Last Name must be entered", "Error");
            showMessageDialog("Tax Payer not added", "Error");
            return;
        }
        if (addrssText.getText().trim().isEmpty()) {
            showMessageDialog("Address must be entered", "Error");
            showMessageDialog("Tax Payer not added", "Error");
            return;
        }
        if (incmeTxt.getText().trim().isEmpty()) {
            showMessageDialog("Tax Payer's income must be entered", "Error");
            showMessageDialog("Tax Payer not added", "Error");
            return;
        }
        if (deductbleTxt.getText().trim().isEmpty()) {
            showMessageDialog("Deductible amount must be entered", "Error");
            showMessageDialog("Tax Payer not added", "Error");
            return;
        }
        presenter.addNewTaxPayer();//run add function from presenter

    }//GEN-LAST:event_addBtnActionPerformed

    private void addrssTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrssTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrssTextActionPerformed

    private void lstNameSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstNameSearchBtnActionPerformed
        //search by Last Name
        presenter.performQueryByLastName(lastNameSearch.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_lstNameSearchBtnActionPerformed

    private void tfnSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnSearchBtnActionPerformed
        //search by TFN
        presenter.performQueryByTFN(Integer.parseInt(tfnSearch.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_tfnSearchBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        presenter.showNext();        // show next TaxPayer
    }//GEN-LAST:event_nextBtnActionPerformed

    private void preBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preBtnActionPerformed
        presenter.showPrevious();        // show previous TaxPayer
    }//GEN-LAST:event_preBtnActionPerformed

    private void tfnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnSearchActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        presenter.browse();//browse method from presenter
        // TODO add your handling code here:
    }//GEN-LAST:event_browseBtnActionPerformed

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        presenter.Exit();//exit the program     // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void lastNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameSearchActionPerformed

    private void updteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updteBtnActionPerformed
        if (tfnText.getText().trim().isEmpty()) {//Text field missing error handling
            showMessageDialog("TFN must be entered", "Error");
            showMessageDialog("Tax Payer Not Updated", "Error");
            return;
        }
        if (frstName.getText().trim().isEmpty()) {
            showMessageDialog("First Name must be entered", "Error");
            showMessageDialog("Tax Payer Not Updated", "Error");
            return;
        }
        if (lstNameText.getText().trim().isEmpty()) {
            showMessageDialog("Last Name must be entered", "Error");
            showMessageDialog("Tax Payer Not Updated", "Error");
            return;
        }
        if (addrssText.getText().trim().isEmpty()) {
            showMessageDialog("Address must be entered", "Error");
            showMessageDialog("Tax Payer Not Updated", "Error");
            return;
        }
        if (incmeTxt.getText().trim().isEmpty()) {
            showMessageDialog("Tax Payer's income must be entered", "Error");
            showMessageDialog("Tax Payer Not Updated", "Error");
            return;
        }
        if (deductbleTxt.getText().trim().isEmpty()) {
            showMessageDialog("Deductible amount must be entered", "Error");
            showMessageDialog("Tax Payer Not Updated", "Error");
            return;
        }
        presenter.updateTaxPayer(); //run update method from presenter
        // TODO add your handling code here:
    }//GEN-LAST:event_updteBtnActionPerformed

    private void txHeldTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHeldTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHeldTxtActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBtn;
    private javax.swing.JTextField addrssText;
    private javax.swing.JToggleButton browseBtn;
    private javax.swing.JTextField deductbleTxt;
    private javax.swing.JTextField frstName;
    private javax.swing.JTextField incmeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField lastNameSearch;
    private javax.swing.JToggleButton lstNameSearchBtn;
    private javax.swing.JTextField lstNameText;
    private javax.swing.JToggleButton nextBtn;
    private javax.swing.JTextPane pageNumText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JToggleButton preBtn;
    private javax.swing.JTextPane sumPageNumText;
    private javax.swing.JTextField tfnSearch;
    private javax.swing.JToggleButton tfnSearchBtn;
    private javax.swing.JTextField tfnText;
    private javax.swing.JTextField txHeldTxt;
    private javax.swing.JTextField txReturnedTxt;
    private javax.swing.JToggleButton updteBtn;
    // End of variables declaration//GEN-END:variables

    //implement all abstract from ITaxPayerView
    //set presenter for this view
    public void bind(TaxPayerPresenter taxPayerPresenter) {
        presenter = taxPayerPresenter;// bind presenter and view 
    }

    public void setTfnText(String tfn) {
        tfnText.setText(tfn);
    }

    @Override
    public int getTfnText() {
        return Integer.parseInt(tfnText.getText().trim()); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setFrstName(String fName) {
        frstName.setText(fName);
    }

    @Override
    public String getfstName() {
        return frstName.getText();
    }

    @Override
    public void setLstName(String lName) {
        lstNameText.setText(lName);
    }

    @Override
    public String getLstName() {
        return lstNameText.getText();
    }

    @Override
    public void setAddrssText(String a) {
        addrssText.setText(a);
    }

    @Override
    public String getAddrssText() {
        return addrssText.getText();
    }

    @Override
    public void setPhoneTxtField(String phone) {
        phoneText.setText(phone);
    }

    @Override
    public String getPhoneTxtField() {
        return phoneText.getText();
    }

    @Override
    public void setMaxTextField(String s) {
        sumPageNumText.setText(s);
    }

    @Override
    public String getMaxTextField() {
        return sumPageNumText.getText();
    }

    @Override
    public void setIndexTextField(String s) {
        pageNumText.setText(s);
    }

    @Override
    public String getIndexTextField() {
        return pageNumText.getText();
    }

    @Override
    public void setIncome(String income) {
        incmeTxt.setText(income);
    }

    @Override
    public int getIncome() {
        return Integer.parseInt(incmeTxt.getText().trim());
    }

    @Override
    public void setDeductible(String deductible) {
        deductbleTxt.setText(deductible);
    }

    @Override
    public int getDeductible() {
        return Integer.parseInt(deductbleTxt.getText().trim());
    }

    @Override
    public void setTaxHeld(String taxHeld) {
        txHeldTxt.setText(taxHeld);
    }

    @Override
    public int getTaxHeld() {
        return Integer.parseInt(txHeldTxt.getText().trim());
    }

    @Override
    public void setTaxReturned(String taxReturned) {
        txReturnedTxt.setText(taxReturned);
    }

    @Override
    public int getTaxReturned() {
        return Integer.parseInt(txReturnedTxt.getText().trim());
    }

    @Override
    public void enableNext() {
        nextBtn.setEnabled(true);
    }

    @Override
    public void enablePrevious() {
        preBtn.setEnabled(true);
    }

    @Override
    public void showMessageDialog(String s1, String s2) {
        JOptionPane.showMessageDialog(this, s1, s2, JOptionPane.PLAIN_MESSAGE);
    }

    @Override
    public void setQueryTFN(String s) {
        tfnSearch.setText(s);
    }

    @Override
    public int getQueryTFN() {
        return Integer.parseInt(tfnSearch.getText());
    }

    @Override
    public void setQueryLName(String s) {
        lastNameSearch.setText(s);
    }

    @Override
    public String getQueryLName() {
        return lastNameSearch.getText();
    }

}
